// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using construccionesMaterIa.Config;

#nullable disable

namespace construccionesMaterIa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250930182735_DbCreated")]
    partial class DbCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("construccionesMaterIa.Models.Camion.Camion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Entrada")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Materiales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Salida")
                        .HasColumnType("datetime2");

                    b.Property<int>("Travellers")
                        .HasColumnType("int");

                    b.Property<bool>("isInRecorrido")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Camiones");
                });
#pragma warning restore 612, 618
        }
    }
}
